# Generated by Django 5.2 on 2025-04-27 03:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='produk/')),
            ],
        ),
        migrations.CreateModel(
            name='Pembelian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('barangs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.barang', verbose_name='Nama Barang')),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('pesanan_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tgl_pesanan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Tunda', 'Tunda'), ('Konfirmasi', 'Konfirmasi'), ('Batal', 'Batal')], default='Tunda', max_length=10)),
                ('jum_barang', models.ManyToManyField(related_name='orders', through='produk.Pembelian', to='produk.barang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pembelian',
            name='pesans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.pesanan', verbose_name='Pesanan'),
        ),
    ]
